#!/usr/bin/env python3
"""Generates SimpaticoQuestions.kt from the iOS source of truth.

    python3 android/scripts/generate_simpatico_questions.py

Reads SimpaticoModels.swift (the `SimpaticoCategory` enum and its display names, and every
question in `SimpaticoQuestionBank.all`) and rewrites the Kotlin question bank. Never edit the
generated file by hand: change the Swift file, then re-run this script.
"""
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
SWIFT = REPO / "SimpaticoModels.swift"
KOTLIN = (REPO / "android/app/src/main/java/com/georgeappdev/atxfriends/domain/simpatico"
          / "SimpaticoQuestions.kt")

STRING = r'"((?:[^"\\]|\\.)*)"'


def swift_unescape(s: str) -> str:
    if re.search(r"\\(?![\"\\])", s):
        sys.exit(f"Unsupported Swift escape in {s!r}")
    return s.replace('\\"', '"').replace("\\\\", "\\")


def kotlin_literal(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$") + '"'


def constant_name(raw: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", raw).upper()


def parse(source: str):
    enum_body = re.search(r"enum SimpaticoCategory\b.*?\{(.*?)\n\s*var displayName", source, re.S).group(1)
    categories = re.findall(r'^\s*case (\w+)\s*=\s*"(\w+)"\s*$', enum_body, re.M)
    if any(case != raw for case, raw in categories):
        sys.exit("Category raw values differ from case names; update the generator")
    display_body = re.search(r"enum SimpaticoCategory\b.*?var displayName.*?\{(.*?)\n    \}", source, re.S).group(1)
    display = dict(re.findall(r"case \.(\w+):\s*return " + STRING, display_body))

    bank = re.search(r"static let all: \[SimpaticoQuestion\] = \[(.*?)\n    \]\n", source, re.S).group(1)
    blocks = re.findall(r"SimpaticoQuestion\((.*?)\n        \)", bank, re.S)
    questions = []
    for block in blocks:
        qid = re.search(r"id:\s*" + STRING, block).group(1)
        category = re.search(r"category:\s*\.(\w+)", block).group(1)
        prompt = swift_unescape(re.search(r"prompt:\s*" + STRING, block).group(1))
        options = [(oid, swift_unescape(text)) for oid, text in re.findall(
            r"SimpaticoOption\(id:\s*" + STRING + r",\s*text:\s*" + STRING + r"\)", block)]
        # Every SimpaticoOption( in the block must have been parsed — catches format drift.
        if len(options) != block.count("SimpaticoOption("):
            sys.exit(f"Could not parse every option of {qid}")
        questions.append((qid, category, prompt, options))

    if len(questions) != bank.count("SimpaticoQuestion("):
        sys.exit("Could not parse every question in SimpaticoQuestionBank.all")
    ids = [q[0] for q in questions]
    if len(set(ids)) != len(ids):
        sys.exit("Duplicate question IDs")
    known = {case for case, _ in categories}
    if {q[1] for q in questions} - known or known - set(display):
        sys.exit("Category mismatch between questions, enum cases, and display names")
    return categories, display, questions


def render(categories, display, questions) -> str:
    out = [
        "// GENERATED by android/scripts/generate_simpatico_questions.py from",
        "// SimpaticoModels.swift. Do not edit by hand — change the Swift file and re-run.",
        "package com.georgeappdev.atxfriends.domain.simpatico",
        "",
        "/** iOS `SimpaticoCategory`: [raw] is the Swift raw value, [displayName] the chip text. */",
        "enum class SimpaticoCategory(val raw: String, val displayName: String) {",
    ]
    for case, raw in categories:
        out.append(f"    {constant_name(case)}({kotlin_literal(raw)}, {kotlin_literal(display[case])}),")
    out += [
        "}",
        "",
        "/** [id] is what Firestore stores; [text] is what users see. */",
        "data class SimpaticoOption(val id: String, val text: String)",
        "",
        "data class SimpaticoQuestion(",
        "    val id: String,",
        "    val category: SimpaticoCategory,",
        "    val prompt: String,",
        "    val options: List<SimpaticoOption>,",
        ")",
        "",
        "/** iOS `SimpaticoQuestionBank.all`: the fixed questions, in the order they appear in the flow. */",
        "object SimpaticoQuestions {",
        "    val all: List<SimpaticoQuestion> = listOf(",
    ]
    for qid, category, prompt, options in questions:
        out += [
            "        SimpaticoQuestion(",
            f"            id = {kotlin_literal(qid)},",
            f"            category = SimpaticoCategory.{constant_name(category)},",
            f"            prompt = {kotlin_literal(prompt)},",
            "            options = listOf(",
        ]
        for oid, text in options:
            out.append(f"                SimpaticoOption({kotlin_literal(oid)}, {kotlin_literal(text)}),")
        out += ["            ),", "        ),"]
    out += [
        "    )",
        "",
        "    private val byID: Map<String, SimpaticoQuestion> = all.associateBy { it.id }",
        "",
        "    fun question(id: String): SimpaticoQuestion? = byID[id]",
        "}",
        "",
    ]
    return "\n".join(out)


def main():
    categories, display, questions = parse(SWIFT.read_text(encoding="utf-8"))
    KOTLIN.write_text(render(categories, display, questions), encoding="utf-8")
    print(f"Wrote {len(questions)} questions to {KOTLIN.relative_to(REPO)}")


if __name__ == "__main__":
    main()
