#!/usr/bin/env python3
"""Generates ActivityCategories.kt from the iOS source of truth.

    python3 android/scripts/generate_activity_categories.py

Reads Avenue3/ActivityCategories.swift (the `ActivityCategory` enum, its display names, and
the exact-name `map`) and rewrites the Kotlin table. Never edit the generated file by hand:
change the Swift file, then re-run this script.
"""
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
SWIFT = REPO / "Avenue3" / "ActivityCategories.swift"
KOTLIN = (REPO / "android/app/src/main/java/com/georgeappdev/atxfriends/domain/matching"
          / "ActivityCategories.kt")


def parse(source: str):
    enum_body = re.search(r"enum ActivityCategory\b.*?\{(.*?)\n\s*var displayName", source, re.S).group(1)
    cases = re.findall(r"^\s*case (\w+)\s*$", enum_body, re.M)

    display = dict(re.findall(r'case \.(\w+): return "([^"]*)"', source))

    map_body = re.search(r"static let map: \[String: ActivityCategory\] = \[(.*?)\n\s*\]\n", source, re.S).group(1)
    entries = re.findall(r'^\s*"((?:[^"\\]|\\.)*)"\s*:\s*\.(\w+)\s*,', map_body, re.M)

    # Every non-comment line in the map must be an entry we parsed — catches format drift.
    lines = [l.strip() for l in map_body.splitlines()]
    code_lines = [l for l in lines if l and not l.startswith("//")]
    if len(code_lines) != len(entries):
        sys.exit(f"Parsed {len(entries)} entries but found {len(code_lines)} code lines in map")
    names = [n for n, _ in entries]
    if len(set(names)) != len(names):
        sys.exit("Duplicate activity names in the Swift map")
    unknown = {c for _, c in entries} - set(cases)
    if unknown or set(cases) - set(display):
        sys.exit(f"Case mismatch: unknown={unknown}, missing display names={set(cases) - set(display)}")
    return cases, display, entries


def kotlin_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$") + '"'


def render(cases, display, entries) -> str:
    const = {c: re.sub(r"(?<!^)([A-Z])", r"_\1", c).upper() for c in cases}
    out = [
        "// GENERATED by android/scripts/generate_activity_categories.py from",
        "// Avenue3/ActivityCategories.swift. Do not edit by hand — change the Swift file and re-run.",
        "package com.georgeappdev.atxfriends.domain.matching",
        "",
        "/** iOS `ActivityCategory`: [raw] is the Swift case name, [displayName] what users see. */",
        "enum class ActivityCategory(val raw: String, val displayName: String) {",
    ]
    out += [f"    {const[c]}({kotlin_string(c)}, {kotlin_string(display[c])})," for c in cases]
    out += [
        "}",
        "",
        "/**",
        " * Exact activity name → category (case-sensitive, like iOS). Custom user-typed activities",
        " * aren't in the table and never take part in category matching.",
        " */",
        "object ActivityCategories {",
        f"    /** {len(entries)} entries, in Swift source order. */",
        "    val map: Map<String, ActivityCategory> = linkedMapOf(",
    ]
    out += [f"        {kotlin_string(n)} to ActivityCategory.{const[c]}," for n, c in entries]
    out += [
        "    )",
        "",
        "    fun category(activityName: String): ActivityCategory? = map[activityName]",
        "}",
        "",
    ]
    return "\n".join(out)


def main():
    cases, display, entries = parse(SWIFT.read_text(encoding="utf-8"))
    KOTLIN.parent.mkdir(parents=True, exist_ok=True)
    KOTLIN.write_text(render(cases, display, entries), encoding="utf-8")
    print(f"Wrote {KOTLIN.relative_to(REPO)}: {len(cases)} categories, {len(entries)} activities")
    if "--tsv" in sys.argv:
        for n, c in entries:
            print(f"{n}\t{c}")


if __name__ == "__main__":
    main()
