// GENERATED by android/scripts/generate_simpatico_questions.py from
// SimpaticoModels.swift. Do not edit by hand — change the Swift file and re-run.
package com.georgeappdev.atxfriends.domain.simpatico

/** iOS `SimpaticoCategory`: [raw] is the Swift raw value, [displayName] the chip text. */
enum class SimpaticoCategory(val raw: String, val displayName: String) {
    HANGING_OUT("hangingOut", "Hanging Out"),
    SOCIAL_STYLE("socialStyle", "Social Style"),
    LIFESTYLE("lifestyle", "Lifestyle"),
}

/** [id] is what Firestore stores; [text] is what users see. */
data class SimpaticoOption(val id: String, val text: String)

data class SimpaticoQuestion(
    val id: String,
    val category: SimpaticoCategory,
    val prompt: String,
    val options: List<SimpaticoOption>,
)

/** iOS `SimpaticoQuestionBank.all`: the fixed questions, in the order they appear in the flow. */
object SimpaticoQuestions {
    val all: List<SimpaticoQuestion> = listOf(
        SimpaticoQuestion(
            id = "saturday",
            category = SimpaticoCategory.HANGING_OUT,
            prompt = "Free Saturday, I'd rather…",
            options = listOf(
                SimpaticoOption("outdoors", "Get outside and active"),
                SimpaticoOption("explore", "Explore somewhere new"),
                SimpaticoOption("chill", "Chill at someone's place"),
                SimpaticoOption("goOut", "Go out: bars, shows, events"),
            ),
        ),
        SimpaticoQuestion(
            id = "hangSize",
            category = SimpaticoCategory.HANGING_OUT,
            prompt = "My ideal hang is…",
            options = listOf(
                SimpaticoOption("oneOnOne", "One-on-one"),
                SimpaticoOption("smallCrew", "A small crew (3–5)"),
                SimpaticoOption("bigGroup", "The bigger the better"),
            ),
        ),
        SimpaticoQuestion(
            id = "planning",
            category = SimpaticoCategory.HANGING_OUT,
            prompt = "When it comes to plans, I'm…",
            options = listOf(
                SimpaticoOption("planner", "A planner"),
                SimpaticoOption("loose", "Loose plan, figure it out day-of"),
                SimpaticoOption("spontaneous", "Spontaneous: text me in an hour"),
            ),
        ),
        SimpaticoQuestion(
            id = "bestTime",
            category = SimpaticoCategory.HANGING_OUT,
            prompt = "I'm at my best…",
            options = listOf(
                SimpaticoOption("earlyMorning", "Early mornings"),
                SimpaticoOption("daytime", "Daytime"),
                SimpaticoOption("evening", "Evenings"),
                SimpaticoOption("lateNight", "Late nights"),
            ),
        ),
        SimpaticoQuestion(
            id = "socialBattery",
            category = SimpaticoCategory.SOCIAL_STYLE,
            prompt = "After a big social weekend, I feel…",
            options = listOf(
                SimpaticoOption("energized", "Energized: what's next?"),
                SimpaticoOption("quietDay", "Good, but I need a quiet day"),
                SimpaticoOption("wiped", "Wiped for a few days"),
            ),
        ),
        SimpaticoQuestion(
            id = "convoDepth",
            category = SimpaticoCategory.SOCIAL_STYLE,
            prompt = "With a new friend, I like conversations…",
            options = listOf(
                SimpaticoOption("light", "Light and fun"),
                SimpaticoOption("mix", "A mix"),
                SimpaticoOption("deep", "Deep pretty quick"),
            ),
        ),
        SimpaticoQuestion(
            id = "texting",
            category = SimpaticoCategory.SOCIAL_STYLE,
            prompt = "Between hangouts, I text…",
            options = listOf(
                SimpaticoOption("daily", "Daily-ish"),
                SimpaticoOption("fewTimesWeek", "A few times a week"),
                SimpaticoOption("plansOnly", "Only to make plans"),
            ),
        ),
        SimpaticoQuestion(
            id = "humor",
            category = SimpaticoCategory.SOCIAL_STYLE,
            prompt = "My humor is…",
            options = listOf(
                SimpaticoOption("dry", "Dry and sarcastic"),
                SimpaticoOption("silly", "Silly and goofy"),
                SimpaticoOption("dark", "Dark"),
                SimpaticoOption("wholesome", "Wholesome"),
            ),
        ),
        SimpaticoQuestion(
            id = "drinking",
            category = SimpaticoCategory.LIFESTYLE,
            prompt = "Drinking: I…",
            options = listOf(
                SimpaticoOption("regularly", "Drink regularly"),
                SimpaticoOption("socially", "Drink socially"),
                SimpaticoOption("rarely", "Rarely drink"),
                SimpaticoOption("never", "Don't drink"),
            ),
        ),
        SimpaticoQuestion(
            id = "nightOutCost",
            category = SimpaticoCategory.LIFESTYLE,
            prompt = "A fun night out should cost…",
            options = listOf(
                SimpaticoOption("under20", "Under \$20"),
                SimpaticoOption("20to50", "\$20–50"),
                SimpaticoOption("over50", "\$50+"),
                SimpaticoOption("whatever", "Whatever, if it's worth it"),
            ),
        ),
        SimpaticoQuestion(
            id = "punctuality",
            category = SimpaticoCategory.LIFESTYLE,
            prompt = "Being on time means…",
            options = listOf(
                SimpaticoOption("early", "Early is on time"),
                SimpaticoOption("tenMin", "Within 10 minutes is fine"),
                SimpaticoOption("suggestion", "Time is a suggestion"),
            ),
        ),
        SimpaticoQuestion(
            id = "schedule",
            category = SimpaticoCategory.LIFESTYLE,
            prompt = "My schedule is…",
            options = listOf(
                SimpaticoOption("nineToFive", "Steady 9-to-5"),
                SimpaticoOption("shifts", "Shifts, all over the place"),
                SimpaticoOption("flexible", "Pretty flexible"),
                SimpaticoOption("parent", "Parent life: it's chaos"),
            ),
        ),
    )

    private val byID: Map<String, SimpaticoQuestion> = all.associateBy { it.id }

    fun question(id: String): SimpaticoQuestion? = byID[id]
}
